Centerhum.SmartFood.Web.Admin/Controllers/BoardController.cs
using Centerhum.SmartFood.DataLayer;
using Centerhum.SmartFood.HtmlObjects;
using Centerhum.SmartFood.Model;
using Centerhum.SmartFood.Web.Admin.Base;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Centerhum.SmartFood.Web.Admin.Controllers
{
    public class BoardController : SmartFoodControllerBase
    {
        public ActionResult CreateInsertBoardForm()
        {
            return PartialView("_CreateInsertBoardForm");
        }
    }
}

Centerhum.SmartFood.Web.Admin/Controllers/HomeController.cs
using Centerhum.SmartFood.DataLayer;
using Centerhum.SmartFood.HtmlObjects;
using Centerhum.SmartFood.Model;
using Centerhum.SmartFood.Web.Admin.Base;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Centerhum.SmartFood.Web.Admin.Controllers
{
    public class HomeController : SmartFoodControllerBase
    {
        public ActionResult Index()
        {
            var frontPage = HomeViewsConfig.Instance.Index();
            return View(frontPage);
        }
    }
}

Centerhum.SmartFood.Web.Admin/Views/Board/_CreateInsertBoardForm.cshtml
<div id="form-insert" class="row">
    <div class="col-md-12">
        <div class="widget box">
            <div class="widget-header">
                <h4>
                    <i class="icon-reorder"></i>Nova Mesa
                </h4>
            </div>
            <div class="widget-content">
                <form id="frmNewBoard" class="form-horizontal row-border form-ajax" action="@Url.Action("Insert", "Board")">
                    <div class="form-body">
                        <div class="form-group">

                            <label class="control-label col-md-3">Nome da Mesa</label>
                            <div class="col-md-9">
                                <input type="text" class="form-control required" name="Name" placeholder="" value="" />
                            </div>

                        </div>

                        <div class="form-group">

                            <div class="col-md-12">
                                <div class="widget box">
                                    <div class="widget-header">
                                        <h4><i class="icon-reorder"></i> Dual List Box</h4>
                                    </div>
                                    <div class="widget-content clearfix">
                                        <div class="left-box">
                                            <input type="text" id="box1Filter" class="form-control box-filter" placeholder="Filter entries..."><button type="button" id="box1Clear" class="filter">x</button>
                                            <select id="box1View" multiple="multiple" class="multiple">
                                                <option value="501649">2008-2009 "Mini" Baja</option>
                                                <option value="501497">AAPA - Asian American Psychological Association</option>
                                                <option value="501053">Academy of Film Geeks</option>
                                                <option value="500001">Accounting Association</option>
                                                <option value="501227">ACLU</option>
                                                <option value="501610">Active Minds</option>
                                                <option value="501514">Activism with A Reel Edge (A.W.A.R.E.)</option>
                                                <option value="501656">Adopt a Grandparent Program</option>
                                                <option value="501050">Africa Awareness Student Organization</option>
                                                <option value="501075">African Diasporic Cultural RC Interns</option>
                                                <option value="501493">Agape</option>
                                                <option value="501562">AGE-Alliance for Graduate Excellence</option>
                                                <option value="500676">AICHE (American Inst of Chemical Engineers)</option>
                                                <option value="501460">AIDS Sensitivity Awareness Project ASAP</option>
                                                <option value="500004">Aikido Club</option>
                                                <option value="500336">Akanke</option>
                                            </select>
                                            <span id="box1Counter" class="count-label">Showing 16 of 16</span> <select id="box1Storage" style="display: none;"></select>
                                        </div>
                                        <div class="dual-control">
                                            <button id="to2" type="button" class="btn">&nbsp;&gt;&nbsp;</button>
                                            <button id="allTo2" type="button" class="btn">&nbsp;&gt;&gt;&nbsp;</button><br>
                                            <button id="to1" type="button" class="btn">&nbsp;&lt;&nbsp;</button>
                                            <button id="allTo1" type="button" class="btn">&nbsp;&lt;&lt;&nbsp;</button>
                                        </div>
                                        <div class="right-box">
                                            <input type="text" id="box2Filter" class="form-control box-filter" placeholder="Filter entries...">
                                            <button type="button" id="box2Clear" class="filter">x</button>
                                            <select id="box2View" multiple="multiple" class="multiple selectEOQ"></select>
                                            <span id="box2Counter" class="count-label">Showing 0 of 0</span> <select id="box2Storage" style="display: none;"></select>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

Centerhum.SmartFood.Web.Admin/Views/Home/Index.cshtml
@model Centerhum.SmartFood.HtmlObjects.FrontPage

@{
    ViewBag.Title = "Dashboard";
    Html.RenderPartial("_FormHeader", Model.FormHeader);
}

@section Scripts {
    <script src="~/Content/smartfood/js/helper.js"></script>
}

<div class="row">

    <div class="col-md-2">
        <div class="statbox widget box box-shadow">
            <div class="widget-content">
                <div class="visual green"> <i class="icon-home"></i> </div>
                <div class="title">&nbsp;</div>
                <div class="value">Abrir Delivery</div>
                <a class="more" href="javascript:void(0);">Clique Aqui <i class="pull-right icon-angle-right"></i></a>
            </div>
        </div>
    </div>

    <div class="col-md-2">
        <div class="statbox widget box box-shadow">
            <div class="widget-content">
                <div class="visual yellow"> <i class="icon-plus"></i> </div>
                <div class="title">&nbsp;</div>
                <div class="value">Abrir Mesa</div>
                <a class="more" href="javascript:void(0);" data-reveal-id="newModal">Clique Aqui <i class="pull-right icon-angle-right"></i></a>
            </div>
        </div>
    </div>

    <div class="col-md-2">
        <div class="statbox widget box box-shadow">
            <div class="widget-content">
                <div class="visual yellow"> <i class="icon-plus"></i> </div>
                <div class="title">&nbsp;</div>
                <div class="value">Abrir Mesa Rapida</div>
                <a class="more" href="javascript:void(0);" data-reveal-id="newModal">Clique Aqui <i class="pull-right icon-angle-right"></i></a>
            </div>
        </div>
    </div>

    <div class="col-md-6">
        <div class="widget">
            <div class="widget-content" style="display: block;">
                <div class="tabbable tabbable-custom">
                    <ul class="nav nav-tabs">
                        <li class="active"><a href="#tab_feed_1" data-toggle="tab">Mesas Abertas</a></li>
                    </ul>
                    <div class="tab-content">
                        <div class="tab-pane active" id="tab_feed_1" style="max-height:155px; overflow-y:auto;">
                            <ul class="feeds clearfix">
                                <li style="cursor:pointer;"> <div class="col1"> <div class="content"> <div class="content-col1"> <div class="label label-success"> <i class="icon-bell"></i> </div> </div> <div class="content-col2"> <div class="desc">Mesa do Noel</div> </div> </div> </div> <div class="col2"> <div class="date"> 17:45 </div> </div> </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="widget box">
            <div class="widget-header">
                <h4><i class="icon-reorder"></i> Dual List Box</h4>
            </div>
            <div class="widget-content clearfix">
                <div class="left-box">
                    <input type="text" id="box1Filter" class="form-control box-filter" placeholder="Filter entries..."><button type="button" id="box1Clear" class="filter">x</button>
                    <select id="box1View" multiple="multiple" class="multiple">
                        <option value="501649">2008-2009 "Mini" Baja</option>
                        <option value="501497">AAPA - Asian American Psychological Association</option>
                        <option value="501053">Academy of Film Geeks</option>
                        <option value="500001">Accounting Association</option>
                        <option value="501227">ACLU</option>
                        <option value="501610">Active Minds</option>
                        <option value="501514">Activism with A Reel Edge (A.W.A.R.E.)</option>
                        <option value="501656">Adopt a Grandparent Program</option>
                        <option value="501050">Africa Awareness Student Organization</option>
                        <option value="501075">African Diasporic Cultural RC Interns</option>
                        <option value="501493">Agape</option>
                        <option value="501562">AGE-Alliance for Graduate Excellence</option>
                        <option value="500676">AICHE (American Inst of Chemical Engineers)</option>
                        <option value="501460">AIDS Sensitivity Awareness Project ASAP</option>
                        <option value="500004">Aikido Club</option>
                        <option value="500336">Akanke</option>
                    </select>
                    <span id="box1Counter" class="count-label">Showing 16 of 16</span> <select id="box1Storage" style="display: none;"></select>
                </div>
                <div class="dual-control">
                    <button id="to2" type="button" class="btn">&nbsp;&gt;&nbsp;</button> <button id="allTo2" type="button" class="btn">&nbsp;&gt;&gt;&nbsp;</button><br> <button id="to1" type="button" class="btn">&nbsp;&lt;&nbsp;</button> <button id="allTo1" type="button" class="btn">&nbsp;&lt;&lt;&nbsp;</button>
                </div>
                <div class="right-box">
                    <input type="text" id="box2Filter" class="form-control box-filter" placeholder="Filter entries...">
                    <button type="button" id="box2Clear" class="filter">x</button>
                    <select id="box2View" multiple="multiple" class="multiple selectEOQ"></select>
                    <span id="box2Counter" class="count-label">Showing 0 of 0</span> <select id="box2Storage" style="display: none;"></select>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="newModal" class="reveal-modal">
    
</div>

Centerhum.SmartFood.Web.Admin/Views/Shared/EntityEmpty.cshtml
<div class="col-md-12">
    <div class="row row-bg align-center">
        <h1></h1>
    </div>
    <div class="row align-center">
        <h5></h5>
    </div>
</div>

Centerhum.SmartFood.Web.Admin/Views/Shared/_BreadcrumbsLine.cshtml
<!-- Breadcrumbs line -->
<div class="crumbs">
	<ul id="breadcrumbs" class="breadcrumb">
        <li>
			<i class="icon-home"></i>
			<a href="@Url.Action("", "")">Home</a>
		</li>       
	</ul>
</div>
<!-- /Breadcrumbs line -->

Centerhum.SmartFood.Web.Admin/Views/Shared/_Form.cshtml
@model List<Centerhum.SmartFood.HtmlObjects.FieldItem>

Centerhum.SmartFood.Web.Admin/Views/Shared/_FormControls.cshtml
@using Centerhum.SmartFood.HtmlObjects.Enum
@model Centerhum.SmartFood.HtmlObjects.FormInsert
@if (Model == null)
{
    return;
}
@{ 
    string formAjax = Model.IsAjax ? "form-insert-ajax" : "";
    string validateForm = !Model.CustomValidate ? "validate-me" : "";
}
<div id="form-insert" class="row">
    <div class="col-md-12">
        <div class="widget box">
            <div class="widget-header">
                <h4>
                    <i class="icon-reorder"></i>@Model.Title</h4>
            </div>
            <div class="widget-content">
                <form id="@Model.FormId" class="form-horizontal row-border @validateForm @formAjax" action="@Url.Action(Model.ActionToPost)">
                    <div class="form-body">

                        @if (Model.Fields != null || Model.Fields.Count() == 0)
                        {
                            foreach (var field in Model.Fields)
                            {
                            <div class="form-group">
                                @{ string requiredClass = ""; }
                                @if (field.Type != FieldType.Divider)
                                {
                                    <label class="control-label col-md-3">
                                        @field.Label

                                        @if (field.IsRequired)
                                        {
                                            requiredClass = "required";
                                            <span class="required">*</span>
                                        }
                                    </label>
                                }
                                <div class="col-md-9">
                                    @switch (field.Type)
                                    {
                                        case Centerhum.SmartFood.HtmlObjects.Enum.FieldType.TextBox:
                                        <input type="text" class="form-control @requiredClass" name="@field.Name" placeholder="@field.Placeholder" />
                                            if (!string.IsNullOrWhiteSpace(field.HelpText))
                                            { <span class="help-block">@field.HelpText</span> }
                                            break;
                                        case Centerhum.SmartFood.HtmlObjects.Enum.FieldType.Email:
                                        <input type="text" class="form-control email @requiredClass" name="@field.Name" placeholder="@field.Placeholder" />
                                            if (!string.IsNullOrWhiteSpace(field.HelpText))
                                            { <span class="help-block">@field.HelpText</span> }
                                            break;
                                        case Centerhum.SmartFood.HtmlObjects.Enum.FieldType.Divider:
                                        <span class="divider-label">@field.Label</span>
                                            break;
                                        case Centerhum.SmartFood.HtmlObjects.Enum.FieldType.Datepicker:
                                        <input type="text" class="form-control date-picker @requiredClass" name="@field.Name" placeholder="@field.Placeholder" />
                                            if (!string.IsNullOrWhiteSpace(field.HelpText))
                                            { <span class="help-block">@field.HelpText</span> }
                                            break;
                                        case Centerhum.SmartFood.HtmlObjects.Enum.FieldType.TextTag:
                                            string tagsValues = "";
                                            field.InitialsTags.ForEach(x => tagsValues += (x + ","));
                                        <input type="text" class="form-control tag @requiredClass" name="@field.Name" placeholder="@field.Placeholder" value="@tagsValues">
                                            if (!string.IsNullOrWhiteSpace(field.HelpText))
                                            { <span class="help-block">@field.HelpText</span> }
                                            break;
                                        case Centerhum.SmartFood.HtmlObjects.Enum.FieldType.Spinner:
                                        <input type="text" class="form-control spinner @requiredClass" name="@field.Name" placeholder="@field.Placeholder">
                                            if (!string.IsNullOrWhiteSpace(field.HelpText))
                                            { <span class="help-block">@field.HelpText</span> }
                                            break;
                                        case Centerhum.SmartFood.HtmlObjects.Enum.FieldType.Select:
                                        <select name="@field.Name" data-placeholder="@field.Placeholder" class="input-block-level">
                                            @if (field.SelectListItems != null || field.SelectListItems.Count() > 0)
                                            {
                                                if (!string.IsNullOrWhiteSpace(field.Placeholder))
                                                {
                                                <option value=""></option>
                                                }

                                                foreach (var option in field.SelectListItems)
                                                {
                                                    if (option.Selected)
                                                    { <option value="@option.Value" selected>@option.Text</option> }
                                                    else
                                                    { <option value="@option.Value">@option.Text</option>  }
                                                }
                                            }
                                        </select>
                                            if (!string.IsNullOrWhiteSpace(field.HelpText))
                                            { <span class="help-block">@field.HelpText</span> }
                                            break;
                                        case Centerhum.SmartFood.HtmlObjects.Enum.FieldType.RadioButton:
                                            if (field.RadioButtonItems != null || field.RadioButtonItems.Count() > 0)
                                            {
                                                foreach (var radio in field.RadioButtonItems)
                                                {
                                        <label class="radio">
                                            <input type="radio" name="@field.Name" value="@radio.Value" class="uniform">
                                            @radio.Label
                                        </label>
                                                }
                                            }
                                            break;
                                        case Centerhum.SmartFood.HtmlObjects.Enum.FieldType.CheckedBox:
                                            if (field.CheckedBoxItems != null || field.CheckedBoxItems.Count() > 0)
                                            {
                                                foreach (var cb in field.CheckedBoxItems)
                                                {
                                        <label class="checkbox">
                                            <div class="checker">
                                                <input type="checkbox" name="@cb.Name" value="true" class="uniform">
                                            </div>
                                            @cb.Label
                                        </label>
                                                }
                                            }
                                            break;
                                        case Centerhum.SmartFood.HtmlObjects.Enum.FieldType.TextArea:
                                            if (field.TextAreaOptions.MaxLength > 0)
                                            {
                                        <textarea rows="3"cols="5" name="@field.Name" class="@requiredClass limited form-control" data-limit="@field.TextAreaOptions.MaxLength" maxlength="@field.TextAreaOptions.MaxLength"></textarea>    
                                            }
                                            else
                                            {
                                        <textarea rows="3"cols="5" name="@field.Name" class="@requiredClass form-control"></textarea>
                                            }
                                            if (field.TextAreaOptions.CreateAutoHelpText)
                                            {
                                        <span class="help-block" id="limit-text">Campo limitado com 250 caracteres.</span>    
                                            }
                                            break;
                                        default:
                                        <input type="text" class="form-control @requiredClass" name="@field.Name" placeholder="@field.Placeholder" />
                                            if (!string.IsNullOrWhiteSpace(field.HelpText))
                                            { <span class="help-block">@field.HelpText</span> }
                                            break;
                                    }
                                </div>
                            </div>
                            }
                        }
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

Centerhum.SmartFood.Web.Admin/Views/Shared/_Layout.cshtml
@using System.Configuration
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0" />
	<title>SmartFood - Tezzo Maki</title>
    @{
        Html.RenderPartial("_Styles");
    }    
    @RenderSection("Styles", false)
</head>
<body>
    <input type="hidden" value="@Url.Content("~/Content/plugins/datatables/tabletools/swf/copy_csv_xls_pdf.swf")" id="urlSwfGrid"/>

    <header class="header navbar navbar-fixed-top" role="banner" id="headerPage">
    @{
        
        Html.RenderPartial("_Header");
    }
    </header>
	<div id="container">
        @*@{Html.RenderPartial("_Slidebar");}*@
		<div id="content">
			<div class="container">
				@{
                    Html.RenderPartial("_BreadcrumbsLine");
                    Html.RenderPartial("_PageHeader");
                }				

				<!--=== Page Content ===-->
				@RenderBody()
				<!-- /Page Content -->
			</div>
			<!-- /.container -->

		</div>
	</div>
        @{Html.RenderPartial("_Scripts");}
        @RenderSection("Scripts", false)
</body>
</html>

Centerhum.SmartFood.Web.Admin/Views/Shared/_PageHeader.cshtml
<!--=== Page Header ===-->
<div class="page-header">
	@*<div class="page-title">
		<h3>@ViewBag.Title</h3>
	</div>*@
</div>
<!-- /Page Header -->

Centerhum.SmartFood.Web.Admin/Views/Shared/_Scripts.cshtml
<!--=== JavaScript ===-->

<script type="text/javascript" src="@Url.Content("~/Content/assets/js/libs/jquery-2.1.3.min.js")"></script>
<script type="text/javascript" src="@Url.Content("~/Content/plugins/jquery-ui/jquery-ui-1.10.2.custom.min.js")"></script>
<script type="text/javascript" src="@Url.Content("~/Content/assets/js/libs/lodash.compat.min.js")"></script>
<script type="text/javascript" src="@Url.Content("~/Content/plugins/respond/respond.min.js")"></script>
@Scripts.Render("~/Content/js/essentials")
<script src="@Url.Content("~/Content/plugins/datatables/tabletools/TableTools.min.js")" type="text/javascript"></script>

Centerhum.SmartFood.Web.Admin/Views/Shared/_Slidebar.cshtml
<div id="sidebar" class="sidebar-fixed">
    <div id="sidebar-content">
        @*	<!-- Search Input -->
		<form class="sidebar-search">
			<div class="input-box">
				<button type="submit" class="submit">
					<i class="icon-search"></i>
				</button>
				<span>
					<input type="text" placeholder="Pesquisar...">
				</span>
			</div>
		</form>*@
        <!--=== Navigation ===-->
        <ul id="nav">
            <li class="">
                <a href="@Url.Action("Index", "Home")"><i class="icon-bar-chart"></i>Resumo</a>
            </li>   
            <li class="current open">
                <a href="javascript:void(0);">
                    <i class="icon-desktop"></i>Adicionar Mesa
                </a>
                <ul class="sub-menu">                    
                    <li><a href="javascript:void(0);" class="subMenuClickEvent"><i class="icon-globe"></i>Item 2 <span class="arrow"></span><i class="arrow icon-angle-down"></i></a>
                        <ul class="sub-menu" style="display: block;">
                            <li><a href="javascript:void(0);"><i class="icon-user"></i>Sample Link 1</a></li>
                            <li><a href="javascript:void(0);"><i class="icon-external-link"></i>Sample Link 1</a></li>
                            <li><a href="javascript:void(0);"><i class="icon-bell"></i>Sample Link 1</a></li>
                        </ul>
                    </li>
                    <li><a href="@Url.Action("Insert", "Document")"><i class="icon-angle-right"></i>Novo </a></li>
                    <li><a href="@Url.Action("History", "Document")""><i class="icon-angle-right"></i>Histórico </a></li>
                </ul>
            </li>
            <li class="">
                <a href="@Url.Action("Index", "Operation")"><i class="icon-file-text-alt"></i>Operação</a>
            </li>
        </ul>
    </div>
    <div id="divider" class="resizeable">
    </div>
</div>
<!-- /Sidebar -->

Centerhum.SmartFood.Web.Admin/Views/Shared/_Styles.cshtml
<link href="@Url.Content("~/Content/bootstrap/css/bootstrap.css")" type="text/css" rel="Stylesheet" />
@Styles.Render("~/Content/assets/css/essentials")
<link href="@Url.Content("~/Content/chubb/css/style.css")" type="text/css" rel="Stylesheet" />
<link href="@Url.Content("~/Content/assets/css/plugins.css")" type="text/css" rel="Stylesheet" />
<link href="@Url.Content("~/Content/assets/css/fontawesome/font-awesome.css")" type="text/css" rel="Stylesheet" />


<link href="@Url.Content("~/Content/plugins/PrettyJson/pretty-json.css")" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Content/plugins/vertical-timeline/css/style.css")" rel="stylesheet" type="text/css"  />

<!-- jQuery UI -->
<!--<link href="@Url.Content("~/Content/plugins/jquery-ui/jquery-ui-1.10.2.custom.css")" rel="stylesheet" type="text/css" />-->
<!--[if lt IE 9]>
	<link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/plugins/jquery-ui/jquery.ui.1.10.2.ie.css")"/>
<![endif]-->

<!--[if IE 7]>
	<link rel="stylesheet" href="@Url.Content("~/Content/assets/css/fontawesome/font-awesome-ie7.css")">
<![endif]-->

<!--[if IE 8]>
	<link href="@Url.Content("~/Content/assets/css/ie8.css")" rel="stylesheet" type="text/css" />
<![endif]-->
@*<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,600,700' rel='stylesheet' type='text/css'>*@

Centerhum.SmartFood.Web.Admin/Views/Shared/_UserSection.cshtml
@model System.String
<li class="dropdown user">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown"></i><span class="username">@Model</span></a>
</li>